### ISSUE TITLE
关于分类的问题

### ISSUE THREAD

**Issue by ciaranchen** [CHCP/hkc-docs#1]
1. 一级分类问题。

    我觉得对于`H2 人与神的关系`分类的解释有点难以接受。首先在README中`2.2.5 宗教`这个部分已经超过了原本各种相，已经在分类以外了，这不严谨。其次是README中提到`佛教却不承认有神的存在`，然后`H2`就命名为`人与神的关系`，这是矛盾的。其三，如果要使用HKC，则必须承认`神`是与`自我`，`人`和`自然`同等存在的，这会使得这个分类方式很难推广。

    我觉得如果能将`宗教`部分并入`H3`，并且直接以`我相`、`人相`、`众生相`、`寿者相`作为一级分类的标题，那会比较好。

2. 二级分类问题。

    虽然在Github的README中解释了第一级分类`Hx`的由来，但是没有解释里面第二级分类`00x`的由来。这样可能会有很多疑惑，而这些疑惑并没有在某处得到解答。例如：

    - 单独列出`900 新技术`的意义。
    - 分离`600 科学`与`700 技术`的意义。
    - `160 瑜伽学`在`100 哲学`分类下的意义。
    - `201 新宗教`与`202 邪教`的意义

3. 脱离图书馆分类法

    UDC 的局限之处在于它是应用在图书馆分类的方法。所以UDC需要有总论，并且在总论中必须提到`01   书目、目录`，`02 图书馆学`等。但是HKC方法却可以不需要这样做，它自己本身就可以是自解释的，应该不需要在总论中再继续说明`021 HKC总论`。

**Comment by CHCP** [comment]
认真的看了您的建议，感觉您还是很专业的。
1.1、关于宗教的分类问题，其实中国人对这个问题是不敏感的，或者说兴趣甚微，但考虑到全球还有几十亿人有宗教信仰，所以当初还是把这个分类留了下来。在西方的图书馆分类中，第一大类你总能看到跟宗教相关的内容。
1.2、关于佛教分类的问题，佛教确实是一种无神论，又把它归到有神论的宗教确实不适合。这也是曾经困惑我的地方。
1.3、关于人与神的关系。在人未能认识到真实之前，会把所有不能解释的原因都归于神，连牛顿都认为宇宙的创建是源于上帝的第一推动力。你提到的把人与神的关系剔除，这个需要考虑下。不过这个分类关系本来就是不断发展的，也是可以考虑的。

2、分类说明的问题。本来要写一篇文章来解释所有的分类原因的，但一直没有动笔，拖延症啊。
3、这个也可以考虑，当时想的保留0级分类是为了给无法分类的内容保留一个地方可以说明。

再次感谢您的建议。
